#Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'imghost' do
	pod 'DZNEmptyDataSet', '~> 1.8'
	pod 'RealmSwift'
	pod 'ImagePicker'
	pod 'SwiftyJSON'
	pod 'Alamofire', '~> 4.0'
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

  # Pods for imghost

target 'imghostTests' do
	inherit! :search_paths
    # Pods for testing
  end

  target 'imghostUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['SWIFT_VERSION'] = '3.0' # or '2.3'
		end
	end
end
